export const ADD_PINGREDIENT = 'ADD_PINGREDIENT';
export const REMOVE_PINGREDIENT = 'REMOVE_PINGREDIENT';
export const ADD_BINGREDIENT = 'ADD_BINGREDIENT';
export const REMOVE_BINGREDIENT = 'REMOVE_BINGREDIENT';
export const SET_SIZE = 'SET_SIZE';
export const SET_BASE = 'SET_BASE';
export const SET_BINGREDIENTS = 'SET_BINGREDIENTS';
export const FETCH_BINGREDIENTS_FAILED = 'FETCH_BINGREDIENTS_FAILED';
export const SET_PINGREDIENTS = 'SET_PINGREDIENTS';
export const FETCH_PINGREDIENTS_FAILED = 'FETCH_PINGREDIENTS_FAILED';
export const SET_SPICE = "SET_SPICE";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT"
